//
//  HGameEnum.h
//  iGaia
//
//  Created by Sergey Sergeev on 3/13/13.
//
//

#ifndef HGameEnum_h
#define HGameEnum_h

enum E_MOVE_CONTROLLER_DIRECTION
{
    E_MOVE_CONTROLLER_DIRECTION_NONE = 0,
    E_MOVE_CONTROLLER_DIRECTION_NORTH,
    E_MOVE_CONTROLLER_DIRECTION_SOUTH,
    E_MOVE_CONTROLLER_DIRECTION_WEST,
    E_MOVE_CONTROLLER_DIRECTION_EAST,
    E_MOVE_CONTROLLER_DIRECTION_NORTH_EAST,
    E_MOVE_CONTROLLER_DIRECTION_NORTH_WEST,
    E_MOVE_CONTROLLER_DIRECTION_SOUTH_EAST,
    E_MOVE_CONTROLLER_DIRECTION_SOUTH_WEST
};

#endif
