//
//  HSNSEnums.h
//  iGaia-CartoonPanzers
//
//  Created by Sergey Sergeev on 4/15/13.
//
//

#ifndef HSNSEnums_h
#define HSNSEnums_h

#include "HCommon.h"

enum E_SNS_OPERATION_ID
{
    E_SNS_OPERATION_ID_LOGIN = 0,
    E_SNS_OPERATION_ID_IMPORT_SOCIAL_FRIENDS,
    E_SNS_OPERATION_ID_IMPORT_OSIRIS_FRIENDS
};

enum E_SNS_OPERATION_STATUS
{
    E_SNS_OPERATION_STATUS_UNKNOWN = 0,
    E_SNS_OPERATION_STATUS_REQUESTING,
    E_SNS_OPERATION_STATUS_RESPONDING,
    E_SNS_OPERATION_STATUS_TIMEOUT,
    E_SNS_OPERATION_STATUS_SUCCESS,
    E_SNS_OPERATION_STATUS_FAILURE
};

#endif 
